import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "alpha2",
  description: "Generated by Next.js 15 with Tailwind CSS"
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen bg-slate-950 text-slate-50`}>
        <div className="flex min-h-screen flex-col items-center justify-center gap-6 px-6 py-12">
          {children}
        </div>
      </body>
    </html>
  );
}
